### PR TITLE
Adapt w.r.t. coq/coq#15327.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please merge now

**Comment by damien-pous** [comment]
@SkySkimmer 
not sure I can: marked as WIP and all checks have failed...

**Comment by SkySkimmer** [comment]
You are the repo owner, mark it ready and ignore the checks
This is normal for olugin adaptation prs

**Comment by damien-pous** [comment]
done, thanks!

**Pull request merged**
