### PR TITLE
Adapt w.r.t. coq/coq#16488.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
Please merge now

**Comment by damien-pous** [comment]
@SkySkimmer @ppedrot 
I can merge if you wish, but the CI complains that it doesn't compile on coqorg/coq:dev ; fine with you?

By the way, is there a CI setup so that 
- my master branch gets tested against coq:dev (only)
- my v8.16  branch gets tested against coq:8.16 (only)
- commits implementing this are shared by my two branches (i.e., keep a single version of the .yml file)
?

Currently both branches are tested against both images, which is a bit silly, 
Thanks,
Damien

**Comment by SkySkimmer** [comment]
> I can merge if you wish, but the CI complains that it doesn't compile on coqorg/coq:dev ; fine with you?

This is normal for adaptation PRs since the CI ran before the Coq PR was merged.

**Comment by damien-pous** [comment]
ok, merged, then...

**Pull request merged**
